language: php
php:
  - 5.3
  - 5.4
  - 5.5
matrix:
  allow_failures:
    - php: 5.5
env:
  global:
    secure: "2RoFj0l11RstXSJZKtTCGksMRVy2b1ecA0Kp96PM7hbGZ6W3sslvemSD6YWN\nLEbKLZlHrbld98x1z0vXGqMTU6FCaXdYNjym59yOgD8caGBgEzmrs3RmgW5l\n3Q/ZVwB6Ld17tlOrGa6igyJ+P8kWvZP0AcriVZJDW5pH49XEAjU="
before_install:
  - composer self-update --no-interaction --ansi
install:
  - ./.travis.install
script: vendor/bin/phpunit --configuration phpunit.xml.dist
